### ISSUE TITLE
`slc`: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by rjhilgefort** [fspinillo/slackfred#18]
Error when running `slc` command. I had just installed and configured the workflow. First attempt at running the command yielded this error.

[screen shot](http://imgur.com/t7FI5No)
![screen shot](http://imgur.com/t7FI5No)

**Comment by fspinillo** [comment]
Can you open up Alfred preferences and run the workflow with the debug option enabled? I checked the code and am not seeing anything that would indicate what's going on.

**Comment by schwedenmut** [comment]
Actually i got the same error message while first using this workflow after inserting the api key.
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 22:38:22 workflow.py:1971 DEBUG    get_password : fspinillo.alfredv2.slackfred:slack_api_key
22:38:23 workflow.py:1830 ERROR    'NoneType' object has no attribute 'read'
Traceback (most recent call last):
  File "/Users/XXX/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.5C18DF8D-6DA2-417E-B6FF-C3A0EF25C5F6/workflow/workflow.py", line 1828, in run
    func(self)
  File "slackfred-channels.py", line 90, in main
    channels_list = wf.cached_data('channels', wrapper, max_age=120)
  File "/Users/XXX/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.5C18DF8D-6DA2-417E-B6FF-C3A0EF25C5F6/workflow/workflow.py", line 1501, in cached_data
    data = data_func()
  File "slackfred-channels.py", line 88, in wrapper
    return slack_channels(keys=slack_keys())
  File "slackfred-channels.py", line 24, in slack_channels
    slack_auth = web.get('https://slack.com/api/auth.test?token=' + api_key + '&pretty=1').json()
  File "/Users/XXX/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.5C18DF8D-6DA2-417E-B6FF-C3A0EF25C5F6/workflow/web.py", line 193, in json
    return json.loads(self.content, self.encoding or 'utf-8')
  File "/Users/XXX/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.5C18DF8D-6DA2-417E-B6FF-C3A0EF25C5F6/workflow/web.py", line 217, in content
    self._content = self.raw.read()
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by rjhilgefort** [comment]
I just tried the whole setup again and it works great! Sorry if the issue was my fault all along. Thanks for the workflow!

**Comment by fspinillo** [comment]
Awesome! Thanks @schwedenmut for helping out. @rjhilgefort there was some small issues with the workflow missing files at one point. I'll probably be re-working a lot of this once Alfred 3 drops.
